# Quiz 1 : Numpy 기초

## Quiz 1-1
- 모든 원소가 0 인 3X3 행렬을 만들고, 원소의 총 갯수를 구하라. (결과는 9)

In [9]:
import numpy as np

a = np.zeros([3,3])
print(a)
print(a.shape)

N = a.shape[0] * a.shape[1]
print(N)

print(len(a) * len(a[0]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9
9


## Quiz 1-2
- 수강생이 7명인 강의실이 있다. 이 중 발표할 사람 1명을 뽑는 기능을 구현하라.
- numpy.random 모듈의 rand(), randn, randint() 를 각각 사용하여 구현하라.

In [13]:
int(np.random.rand()*7) + 1

2

In [15]:
a = np.random.randn(7)
print(a)

pos = None
max = -np.inf
for i in range(7):
    if a[i]>max:
        pos = i
        max = a[i]
        
print(pos+1, max)

[-0.25442541 -0.02088284 -0.59467799 -1.69382614 -0.12030626 -0.22286259
 -1.31173692]
2 -0.020882835017101208


In [11]:
a = np.random.randn(7)
print(a)

list(a).index(a.max())

[-1.29712125  1.700804    0.97666636 -0.18681409  0.74540148 -0.1832675
 -1.23881842]


1

In [17]:
a = np.random.randn(7)
print(a)

a.argmax() + 1

[ 1.27128021 -0.23392898  0.95692793  0.42397762  0.41399632  0.64167426
  0.45033197]


1

In [20]:
np.random.randint(7) + 1

7

## Quiz 1-3
- 각각 학생이 10명인 학급이 2반 있다.
- 1반은 컴퓨터 시험 점수가 평균이 80, 표준편차가 20이고, 2반은 평균이 70, 표준편차가 30 이다. (점수는 정수이다.)
- 만점이 100점일 때, 20명에 대한 컴퓨터 시험 점수 표를 만들어라.
- 20X2 형태의 어레이로 만들자. 첫번째 열은 점수, 두번째 열은 반번호이다. (1반은 0, 2반은 1)

In [17]:
scores = np.zeros([20,2])

a = np.random.normal(80,20,size=10)
a[a>100] = 100
a = np.array(a,dtype=int)

display(a)

scores[:10,0] = a
display(scores)

array([ 72,  96,  48,  79,  97, 100,  71, 100,  62,  62])

array([[ 72.,   0.],
       [ 96.,   0.],
       [ 48.,   0.],
       [ 79.,   0.],
       [ 97.,   0.],
       [100.,   0.],
       [ 71.,   0.],
       [100.,   0.],
       [ 62.,   0.],
       [ 62.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.]])

In [18]:
b = np.random.normal(70,30,size=10)
b[b>100] = 100
b = np.array(b,dtype=int)

display(b)

scores[10:,0] = b
display(scores)

array([ 92,  92,  64,   9,  61,  65, 100,  73,  58,  59])

array([[ 72.,   0.],
       [ 96.,   0.],
       [ 48.,   0.],
       [ 79.,   0.],
       [ 97.,   0.],
       [100.,   0.],
       [ 71.,   0.],
       [100.,   0.],
       [ 62.,   0.],
       [ 62.,   0.],
       [ 92.,   0.],
       [ 92.,   0.],
       [ 64.,   0.],
       [  9.,   0.],
       [ 61.,   0.],
       [ 65.,   0.],
       [100.,   0.],
       [ 73.,   0.],
       [ 58.,   0.],
       [ 59.,   0.]])

In [34]:
scores[:,1] = [0]*10 + [1]*10
scores

array([[ 96.,   0.],
       [ 87.,   0.],
       [ 69.,   0.],
       [ 53.,   0.],
       [100.,   0.],
       [ 63.,   0.],
       [ 67.,   0.],
       [ 75.,   0.],
       [ 85.,   0.],
       [ 95.,   0.],
       [100.,   1.],
       [ 68.,   1.],
       [ 51.,   1.],
       [ 92.,   1.],
       [ 53.,   1.],
       [ 60.,   1.],
       [ 56.,   1.],
       [ 33.,   1.],
       [ 49.,   1.],
       [ 43.,   1.]])

In [16]:
import mpl_toolkits.basemap

ModuleNotFoundError: No module named 'mpl_toolkits.basemap'

In [15]:
mpl_toolkits.

<module 'mpl_toolkits' (namespace)>