### Introduction to Machine Learning with Python
## Chapter 4. 데이터 표현과 특성 공학
---
# 범주형 변수

In [1]:
%pylab inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [2]:
data = pd.read_csv('adult.data', header=None, skipinitialspace=True)

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
0     32561 non-null int64
1     32561 non-null object
2     32561 non-null int64
3     32561 non-null object
4     32561 non-null int64
5     32561 non-null object
6     32561 non-null object
7     32561 non-null object
8     32561 non-null object
9     32561 non-null object
10    32561 non-null int64
11    32561 non-null int64
12    32561 non-null int64
13    32561 non-null object
14    32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [5]:
data.describe()

0             2             4             10            11  \
count  32561.000000  3.256100e+04  32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05     10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05      2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04      1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05      9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05     10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05     12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000   

                 12  
count  32561.000000  
mean      40.437456  
std       12.347429  
min        1.000000  
25%       40.000000  
50%       40.000000  
75%       45.000000  
max       99.000000

In [6]:
data.head()

0                 1       2          3   4                   5   \
0  39         State-gov   77516  Bachelors  13       Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13  Married-civ-spouse   
2  38           Private  215646    HS-grad   9            Divorced   
3  53           Private  234721       11th   7  Married-civ-spouse   
4  28           Private  338409  Bachelors  13  Married-civ-spouse   

                  6              7      8       9     10  11  12  \
0       Adm-clerical  Not-in-family  White    Male  2174   0  40   
1    Exec-managerial        Husband  White    Male     0   0  13   
2  Handlers-cleaners  Not-in-family  White    Male     0   0  40   
3  Handlers-cleaners        Husband  Black    Male     0   0  40   
4     Prof-specialty           Wife  Black  Female     0   0  40   

              13     14  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [7]:
data.tail()

0             1       2           3   4                   5   \
32556  27       Private  257302  Assoc-acdm  12  Married-civ-spouse   
32557  40       Private  154374     HS-grad   9  Married-civ-spouse   
32558  58       Private  151910     HS-grad   9             Widowed   
32559  22       Private  201490     HS-grad   9       Never-married   
32560  52  Self-emp-inc  287927     HS-grad   9  Married-civ-spouse   

                      6          7      8       9      10  11  12  \
32556       Tech-support       Wife  White  Female      0   0  38   
32557  Machine-op-inspct    Husband  White    Male      0   0  40   
32558       Adm-clerical  Unmarried  White  Female      0   0  40   
32559       Adm-clerical  Own-child  White    Male      0   0  20   
32560    Exec-managerial       Wife  White  Female  15024   0  40   

                  13     14  
32556  United-States  <=50K  
32557  United-States   >50K  
32558  United-States  <=50K  
32559  United-States  <=50K  
32560  United-States   >50K

In [5]:
data2 = data[[0,1,3,9,12,6,14]]
data2.columns = ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']
data2.head()

age         workclass  education  gender  hours-per-week  \
0   39         State-gov  Bachelors    Male              40   
1   50  Self-emp-not-inc  Bachelors    Male              13   
2   38           Private    HS-grad    Male              40   
3   53           Private       11th    Male              40   
4   28           Private  Bachelors  Female              40   

          occupation income  
0       Adm-clerical  <=50K  
1    Exec-managerial  <=50K  
2  Handlers-cleaners  <=50K  
3  Handlers-cleaners  <=50K  
4     Prof-specialty  <=50K

In [6]:
data2.workclass.value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

In [7]:
data2.education.value_counts()

HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: education, dtype: int64

In [8]:
data2.gender.value_counts()

Male      21790
Female    10771
Name: gender, dtype: int64

In [9]:
data2.occupation.value_counts()

Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
?                    1843
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: occupation, dtype: int64

In [10]:
data2.income.value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

In [11]:
data3 = data2.copy()
data3.gender = np.where(data3.gender=='Male',0,1) # 0: Male, 1: Female
data3.income = np.where(data3.income=='<=50K',0,1) # '0: '<=50K', 1: >50K'

In [12]:
data3.head(10)

age         workclass  education  gender  hours-per-week  \
0   39         State-gov  Bachelors       0              40   
1   50  Self-emp-not-inc  Bachelors       0              13   
2   38           Private    HS-grad       0              40   
3   53           Private       11th       0              40   
4   28           Private  Bachelors       1              40   
5   37           Private    Masters       1              40   
6   49           Private        9th       1              16   
7   52  Self-emp-not-inc    HS-grad       0              45   
8   31           Private    Masters       1              50   
9   42           Private  Bachelors       0              40   

          occupation  income  
0       Adm-clerical       0  
1    Exec-managerial       0  
2  Handlers-cleaners       0  
3  Handlers-cleaners       0  
4     Prof-specialty       0  
5    Exec-managerial       0  
6      Other-service       0  
7    Exec-managerial       1  
8     Prof-specialty       1  
9    Exec-managerial       1

In [13]:
data3.workclass.value_counts()

Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64

### pd.get_dummies()

In [15]:
pd.get_dummies(data3.workclass)[:5]

?  Federal-gov  Local-gov  Never-worked  Private  Self-emp-inc  \
0  0            0          0             0        0             0   
1  0            0          0             0        0             0   
2  0            0          0             0        1             0   
3  0            0          0             0        1             0   
4  0            0          0             0        1             0   

   Self-emp-not-inc  State-gov  Without-pay  
0                 0          1            0  
1                 1          0            0  
2                 0          0            0  
3                 0          0            0  
4                 0          0            0

In [16]:
pd.get_dummies(data3.education)[:5]

10th  11th  12th  1st-4th  5th-6th  7th-8th  9th  Assoc-acdm  Assoc-voc  \
0     0     0     0        0        0        0    0           0          0   
1     0     0     0        0        0        0    0           0          0   
2     0     0     0        0        0        0    0           0          0   
3     0     1     0        0        0        0    0           0          0   
4     0     0     0        0        0        0    0           0          0   

   Bachelors  Doctorate  HS-grad  Masters  Preschool  Prof-school  \
0          1          0        0        0          0            0   
1          1          0        0        0          0            0   
2          0          0        1        0          0            0   
3          0          0        0        0          0            0   
4          1          0        0        0          0            0   

   Some-college  
0             0  
1             0  
2             0  
3             0  
4             0

In [17]:
pd.get_dummies(data3.occupation)[:5]

?  Adm-clerical  Armed-Forces  Craft-repair  Exec-managerial  \
0  0             1             0             0                0   
1  0             0             0             0                1   
2  0             0             0             0                0   
3  0             0             0             0                0   
4  0             0             0             0                0   

   Farming-fishing  Handlers-cleaners  Machine-op-inspct  Other-service  \
0                0                  0                  0              0   
1                0                  0                  0              0   
2                0                  1                  0              0   
3                0                  1                  0              0   
4                0                  0                  0              0   

   Priv-house-serv  Prof-specialty  Protective-serv  Sales  Tech-support  \
0                0               0                0      0             0   
1                0               0                0      0             0   
2                0               0                0      0             0   
3                0               0                0      0             0   
4                0               1                0      0             0   

   Transport-moving  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0

In [18]:
data4 = pd.get_dummies(data3)
data4.head()

age  gender  hours-per-week  income  workclass_?  workclass_Federal-gov  \
0   39       0              40       0            0                      0   
1   50       0              13       0            0                      0   
2   38       0              40       0            0                      0   
3   53       0              40       0            0                      0   
4   28       1              40       0            0                      0   

   workclass_Local-gov  workclass_Never-worked  workclass_Private  \
0                    0                       0                  0   
1                    0                       0                  0   
2                    0                       0                  1   
3                    0                       0                  1   
4                    0                       0                  1   

   workclass_Self-emp-inc             ...               \
0                       0             ...                
1                       0             ...                
2                       0             ...                
3                       0             ...                
4                       0             ...                

   occupation_Farming-fishing  occupation_Handlers-cleaners  \
0                           0                             0   
1                           0                             0   
2                           0                             1   
3                           0                             1   
4                           0                             0   

   occupation_Machine-op-inspct  occupation_Other-service  \
0                             0                         0   
1                             0                         0   
2                             0                         0   
3                             0                         0   
4                             0                         0   

   occupation_Priv-house-serv  occupation_Prof-specialty  \
0                           0                          0   
1                           0                          0   
2                           0                          0   
3                           0                          0   
4                           0                          1   

   occupation_Protective-serv  occupation_Sales  occupation_Tech-support  \
0                           0                 0                        0   
1                           0                 0                        0   
2                           0                 0                        0   
3                           0                 0                        0   
4                           0                 0                        0   

   occupation_Transport-moving  
0                            0  
1                            0  
2                            0  
3                            0  
4                            0  

[5 rows x 44 columns]

In [19]:
data4.columns

Index(['age', 'gender', 'hours-per-week', 'income', 'workclass_?',
       'workclass_Federal-gov', 'workclass_Local-gov',
       'workclass_Never-worked', 'workclass_Private', 'workclass_Self-emp-inc',
       'workclass_Self-emp-not-inc', 'workclass_State-gov',
       'workclass_Without-pay', 'education_10th', 'education_11th',
       'education_12th', 'education_1st-4th', 'education_5th-6th',
       'education_7th-8th', 'education_9th', 'education_Assoc-acdm',
       'education_Assoc-voc', 'education_Bachelors', 'education_Doctorate',
       'education_HS-grad', 'education_Masters', 'education_Preschool',
       'education_Prof-school', 'education_Some-college', 'occupation_?',
       'occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Pr

In [20]:
idx = list(range(len(data4.columns)))
idx.pop(3)

X = data4.iloc[:,idx].values
y = data4.iloc[:,3].values

In [21]:
X.shape, y.shape, len(data4.columns)

((32561, 43), (32561,), 44)

In [22]:
y

array([0, 0, 0, ..., 0, 0, 1])

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

model = LogisticRegression()
model.fit(X_train, y_train)
score = model.score(X_test, y_test)
print(score)

0.8075175039921385


In [24]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()
model.fit(X_train, y_train)
score = model.score(X_test, y_test)
print(score)

0.7688244687384842


In [25]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train, y_train)
score = model.score(X_test, y_test)
print(score)

0.7798796216680998


In [26]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)
score = model.score(X_test, y_test)
print(score)

C:\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


0.7835646726446382


In [27]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)
score = model.score(X_test, y_test)
print(score)

0.8071489988944847


### 직접 변환 방법

In [35]:
mapper = dict(zip(data3.occupation.unique(), range(15)))
occu = data3.occupation.map(mapper)
display(occu.shape, occu.head())

(32561,)

0    0
1    1
2    2
3    2
4    3
Name: occupation, dtype: int64

In [38]:
mapper = dict(zip(data3.occupation.unique(), range(15)))
olist = [ mapper[s] for s in data3.occupation ]
olist[:5]

[0, 1, 2, 2, 3]

In [40]:
oh = np.eye(15)[olist]
oh[:5]
# np.c_[X, oh]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

- 값이 숫자라 하더라도 이산적인 특징을 가질 수 있다.
- 이럴 경우, 위와 같은 방법으로 변환하거나 pd.get_dummies() 의 columns 속성으로 지정하면 된다.

In [56]:
from sklearn.preprocessing import OneHotEncoder

OneHotEncoder(sparse=False).fit_transform([[1],[0],[2]])
#OneHotEncoder(sparse=False).fit_transform([[1,2],[0,1],[2,3]])

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

### 구간 분할

In [33]:
np.digitize(range(20), bins=np.arange(0,20,2))

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10], dtype=int64)

In [37]:
from sklearn.datasets import load_iris

iris = load_iris()
c0 = iris.data[:,0]

# 최소값과 최대값 사이를 10개의 구간으로 나눈다. 값이 1부터 시작하므로 1을 빼준다.
dt = np.digitize(c0, np.arange(c0.min(), c0.max(), (c0.max()-c0.min())/10)) - 1
display(dt)

array([2, 1, 1, 0, 1, 3, 0, 1, 0, 1, 3, 1, 1, 0, 4, 3, 3, 2, 3, 2, 3, 2,
       0, 2, 1, 1, 1, 2, 2, 1, 1, 3, 2, 3, 1, 1, 3, 1, 0, 2, 1, 0, 0, 1,
       2, 1, 2, 0, 2, 1, 7, 5, 7, 3, 6, 3, 5, 1, 6, 2, 1, 4, 4, 4, 3, 6,
       3, 4, 5, 3, 4, 4, 5, 4, 5, 6, 6, 6, 4, 3, 3, 3, 4, 4, 3, 4, 6, 5,
       3, 3, 3, 4, 4, 1, 3, 3, 3, 5, 2, 3, 5, 4, 7, 5, 6, 9, 1, 8, 6, 8,
       6, 5, 6, 3, 4, 5, 6, 9, 9, 4, 7, 3, 9, 5, 6, 8, 5, 4, 5, 8, 8, 9,
       5, 5, 4, 9, 5, 5, 4, 7, 6, 7, 4, 6, 6, 6, 5, 6, 5, 4], dtype=int64)

In [38]:
np.eye(10)[dt]

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])